import { useEffect, useRef, useState } from "react";

import { ARCHIVE_ENTRIES } from "@/data/archive";
import { plotInto, plotToBlob, type PlotId } from "@/lib/archive-plot";
import { Reveal } from "./Reveal";

/**
 * ARCHIVE FILES — the four works, taken away at the visitor's own resolution.
 *
 * Sits directly after ArchiveIndex: the record, then the record in your hands,
 * then the objects. Nothing here announces a price or its absence — under hard
 * constraint 11 the brand carries no calls to buy and no promotional furniture,
 * and "free" is furniture. The works are simply available.
 *
 * The download control is a spaced-capitals label, never a filled button.
 * That comes from hard constraint 11 — "no filled rounded SaaS buttons, no
 * gradient decoration". BRAND-GUIDELINES.md governs; the site is downstream.
 *
 * One canvas plots live on scroll-in. That is the demonstration and the reason
 * this section exists at all — the visitor watches 260 passes accumulate until
 * the one that moved appears, which is the argument the whole project makes.
 * The other three are already shown as stills in ArchiveIndex above; repeating
 * four heavy canvases here would be redundant and slow.
 */

const SIZES = [
  { w: 3840, h: 2160, label: "3840 × 2160 — desktop, 4K" },
  { w: 2560, h: 1440, label: "2560 × 1440 — desktop, QHD" },
  { w: 1920, h: 1080, label: "1920 × 1080 — desktop, HD" },
  { w: 1290, h: 2796, label: "1290 × 2796 — phone" },
  { w: 1170, h: 2532, label: "1170 × 2532 — phone" },
] as const;

type Size = { w: number; h: number; label: string };

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function ArchiveFiles() {
  const [sizes, setSizes] = useState<Size[]>([...SIZES]);
  const [chosen, setChosen] = useState(0);
  const [busy, setBusy] = useState<PlotId | null>(null);
  const [note, setNote] = useState<Record<string, string>>({});
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const dpr = window.devicePixelRatio || 1;
    const w = Math.round(window.screen.width * dpr);
    const h = Math.round(window.screen.height * dpr);
    if (w > 0 && h > 0 && w <= 8000 && h <= 8000) {
      setSizes([{ w, h, label: `${w} × ${h} — this screen` }, ...SIZES]);
    }
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    let done = false;
    const draw = () => {
      if (done) return;
      done = true;
      const ctx = canvas.getContext("2d", { willReadFrequently: true });
      if (ctx) plotInto("001", ctx, canvas.width, canvas.height);
    };

    if (typeof IntersectionObserver === "undefined") {
      draw();
      return;
    }
    const io = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            io.disconnect();
            requestAnimationFrame(draw);
          }
        }
      },
      { rootMargin: "200px" },
    );
    io.observe(canvas);
    return () => io.disconnect();
  }, []);

  async function take(id: PlotId, title: string) {
    const size = sizes[chosen];
    setBusy(id);
    setNote((n) => ({ ...n, [id]: `Plotting ${size.w} × ${size.h}…` }));

    await new Promise((r) => requestAnimationFrame(() => r(null)));

    try {
      const blob = await plotToBlob(id, size.w, size.h);
      if (!blob) throw new Error("no blob");
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `tsm-fragment-${id}-${slugify(title)}-${size.w}x${size.h}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
      setNote((n) => ({ ...n, [id]: "" }));
    } catch {
      setNote((n) => ({ ...n, [id]: "That size could not be plotted here." }));
    } finally {
      setBusy(null);
    }
  }

  return (
    <section id="files" className="grain border-t border-metadata/25">
      <div className="mx-auto max-w-5xl px-6 py-24 sm:px-10 sm:py-32">
        <Reveal>
          <p className="label-editorial">The Archive on your screen</p>
          <h2 className="mt-5 max-w-2xl text-3xl leading-tight text-balance sm:text-4xl">
            Plotted at your size, not resized.
          </h2>
          <p className="mt-6 max-w-prose text-sm leading-relaxed text-metadata">
            The works are not stored as images. Each one is re-solved from its
            equation at the exact dimensions you choose, so the line weight and the
            margins stay right at any size. Nothing is upscaled, and nothing here was
            generated by a diffusion model.
          </p>
        </Reveal>

        <Reveal delay={90}>
          <div className="mt-14 grid gap-10 md:grid-cols-[1.1fr_1fr] md:items-start md:gap-16">
            <canvas
              ref={canvasRef}
              width={1000}
              height={563}
              className="w-full border border-metadata/25"
              aria-label="Fragment 001, Return — the same curve plotted two hundred and sixty times"
            />

            <div>
              <label htmlFor="tsm-resolution" className="label-editorial block">
                Resolution
              </label>
              <select
                id="tsm-resolution"
                value={chosen}
                onChange={(e) => setChosen(Number(e.target.value))}
                className="mt-3 w-full border border-metadata/40 bg-transparent px-3 py-2 text-sm text-foreground"
              >
                {sizes.map((s, i) => (
                  <option key={s.label} value={i} className="bg-background">
                    {s.label}
                  </option>
                ))}
              </select>

              <ul className="mt-10 divide-y divide-metadata/25 border-t border-metadata/25">
                {ARCHIVE_ENTRIES.map((entry) => (
                  <li
                    key={entry.id}
                    className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2 py-4"
                  >
                    <div className="min-w-0">
                      <p className="label-editorial">{entry.number}</p>
                      <p className="mt-1 truncate text-base">{entry.title}</p>
                    </div>
                    <div className="flex items-baseline gap-4">
                      {note[entry.id] ? (
                        <span className="label-editorial normal-case">
                          {note[entry.id]}
                        </span>
                      ) : null}
                      <button
                        type="button"
                        className="link-quiet disabled:opacity-50"
                        disabled={busy !== null}
                        onClick={() => take(entry.id as PlotId, entry.title)}
                      >
                        {busy === entry.id ? "Plotting" : "Take"}
                      </button>
                    </div>
                  </li>
                ))}
              </ul>

              <p className="mt-8 max-w-prose text-xs leading-relaxed text-metadata">
                For your own screens. Not for resale or redistribution. The works
                remain the author&rsquo;s.
              </p>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
